[package]
name = "demver"
version = "0.1.0"
authors = ["Basti Destruction <bastidest@mailbox.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-ini = "0.16"
semver = "0.11"
regex = "1"
lazy_static = "1.4.0"
